### ISSUE TITLE
npm start Failed to compile with 4 errors 

### ISSUE THREAD

**Issue by fonero-project** [gxchain/gxchain-wallet#34]
What versions of node and npm are required, I get errors when building:

 ERROR  Failed to compile with 4 errors
These dependencies were not found:
* @/components/WalletCreateStep1 in ./src/router/index.js
* @/components/WalletCreateStep2 in ./src/router/index.js
* @/components/WalletIndex in ./src/router/index.js
To install them, you can run: npm install --save @/components/WalletCreateStep1 @/components/WalletCreateStep2 @/components/WalletIndex
This relative module was not found:
* ./components/sub/LoadingLayer in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue

**Comment by lanhaoxiang** [comment]
```
node -v
```
Make sure node version is newer than 6

**Comment by fonero-project** [comment]
root@dex /opt/gxchain-wallet # node -v
v6.15.1
root@dex /opt/gxchain-wallet # npm -v
3.10.10

**Comment by lanhaoxiang** [comment]
Also make sure dependencies have fully installed.
```
npm install -d
```

**Comment by lanhaoxiang** [comment]
node version 10 or later would be better.

**Comment by fonero-project** [comment]
ERROR  Failed to compile with 4 errors                                                                                                                                                                                            10:59:59 AM

These dependencies were not found:

* @/components/WalletCreateStep1 in ./src/router/index.js
* @/components/WalletCreateStep2 in ./src/router/index.js
* @/components/WalletIndex in ./src/router/index.js

To install them, you can run: npm install --save @/components/WalletCreateStep1 @/components/WalletCreateStep2 @/components/WalletIndex


This relative module was not found:

* ./components/sub/LoadingLayer in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/App.vue
> Listening at http://localhost:8082

(node:18670) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/opt/gxchain-wallet/node_modules/opn/index.js:82:13)
    at Object.apply (/opt/gxchain-wallet/node_modules/harmony-reflect/reflect.js:2064:37)
    at Object.onceWrapper (events.js:273:13)
    at Object.apply (/opt/gxchain-wallet/node_modules/harmony-reflect/reflect.js:2064:37)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Object.apply (/opt/gxchain-wallet/node_modules/harmony-reflect/reflect.js:2064:37)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:616:12)
(node:18670) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18670) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
root@dex /opt/gxchain-wallet # node -v
v11.3.0
root@dex /opt/gxchain-wallet # npm -v
6.4.1
root@dex /opt/gxchain-wallet #

**Comment by fonero-project** [comment]
added 1407 packages from 833 contributors and audited 10729 packages in 102.697s
found 3 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm timing npm Completed in 102921ms
npm info ok

**Comment by fonero-project** [comment]
npm WARN compression-webpack-plugin@2.0.0 requires a peer of webpack@^4.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@2.1.2 requires a peer of webpack@^2.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by fonero-project** [comment]
On any version this error

**Comment by fonero-project** [comment]
People previously wrote the same thing to you, say what requirements, or try repeating the same thing.

**Comment by xLogic92** [comment]
Please check if node-sass is completely downloaded, and make sure that node-sass could find a binding for your current environment. 

For example:
Found bindings for the following environments:
  - OS X 64-bit with Node.js 6.x

You can delete the node_modules and re-run npm install to ensure that node-sass is properly installed.

**Comment by fonero-project** [comment]
ubuntu 16.04

**Comment by fonero-project** [comment]
nvm install v11 && nvm use v11
npm install
npm start

 ERROR  Failed to compile with 4 errors                                                                                                                                                                                             1:08:54 PM

These dependencies were not found:

* @/components/WalletCreateStep1 in ./src/router/index.js
* @/components/WalletCreateStep2 in ./src/router/index.js
* @/components/WalletIndex in ./src/router/index.js

To install them, you can run: npm install --save @/components/WalletCreateStep1 @/components/WalletCreateStep2 @/components/WalletIndex


This relative module was not found:

* ./components/sub/LoadingLayer in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/App.vue
> Listening at http://localhost:8082

(node:27337) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/opt/gxchain-wallet/node_modules/opn/index.js:82:13)
    at Object.apply (/opt/gxchain-wallet/node_modules/harmony-reflect/reflect.js:2064:37)
    at Object.onceWrapper (events.js:273:13)
    at Object.apply (/opt/gxchain-wallet/node_modules/harmony-reflect/reflect.js:2064:37)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Object.apply (/opt/gxchain-wallet/node_modules/harmony-reflect/reflect.js:2064:37)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:616:12)
(node:27337) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27337) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by xLogic92** [comment]
You may be able to run it under mac or windows to troubleshoot whether it is caused by the Ubuntu environment.

**Comment by fonero-project** [comment]
Guys, you are bad developers.
Everything has already been collected, and here node-sass is all right with it.
bye.

**Comment by xLogic92** [comment]
> Guys, you are bad developers.
> Everything has already been collected, and here node-sass is all right with it.
> bye.


I am very sorry, it took you a lot of time to stay together to find the problem. 
The reason for this problem is because ubuntu is case sensitive. You can fix the problem by pulling the latest code now.
